# Generated by Django 4.1.7 on 2023-03-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('cover', models.ImageField(upload_to='', verbose_name='표지 이미지')),
                ('order', models.IntegerField(default=0, help_text='낮을수록 우선순위 높음', verbose_name='정렬순서')),
                ('link_to', models.URLField(blank=True, help_text='ex: https://novel.munpia.com/266932, https://series.naver.com/novel/detail.series?productNo=4775407 등', verbose_name='클릭 시 이동할 경로')),
                ('is_show', models.BooleanField(default=True, verbose_name='테일크루 페이지 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', '-modified_at', '-created_at'),
            },
        ),
    ]
